ETL_Aplicada/Controllers/ClienteController.cs
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Threading.Tasks;
using ETL_Aplicada.Models;
using Microsoft.AspNetCore.Mvc;

namespace ETL_Aplicada.Controllers
{
    public class ClienteController : Controller
    {
        public IActionResult Index()
        {
            ConexionModel con1 = new ConexionModel("Sucursal1");
            ConexionModel con2 = new ConexionModel("Sucursal2");
            ConexionModel con3 = new ConexionModel("Sucursal3");

            SqlDataReader clientes1 = con1.consultar("SELECT * FROM Cliente");
            SqlDataReader clientes2 = con2.consultar("SELECT * FROM Cliente");
            SqlDataReader clientes3 = con3.consultar("SELECT * FROM Cliente");

            List<ClienteModel> lista1 = new List<ClienteModel>();
            List<ClienteModel> lista2 = new List<ClienteModel>();
            List<ClienteModel> lista3 = new List<ClienteModel>();

            while (clientes1.Read()) {
                ClienteModel cml = new ClienteModel();
                cml.id_cliente = int.Parse(clientes1["id_cliente"].ToString());
                cml.cedula = clientes1["cedula"].ToString();
                cml.nombre = clientes1["nombre"].ToString();
                cml.apellido = clientes1["apellido"].ToString();
                cml.email = clientes1["email"].ToString();
                cml.direccion = clientes1["direccion"].ToString();
                cml.telefono = clientes1["telefono"].ToString();

                lista1.Add(cml);
            }

            while (clientes2.Read())
            {
                ClienteModel cml = new ClienteModel();
                cml.id_cliente = int.Parse(clientes2["id_cliente"].ToString());
                cml.cedula = clientes2["cedula"].ToString();
                cml.nombre = clientes2["nombre"].ToString();
                cml.apellido = clientes2["apellido"].ToString();
                cml.email = clientes2["email"].ToString();
                cml.direccion = clientes2["direccion"].ToString();
                cml.telefono = clientes2["telefono"].ToString();

                lista2.Add(cml);
            }

            while (clientes3.Read())
            {
                ClienteModel cml = new ClienteModel();
                cml.id_cliente = int.Parse(clientes3["id_cliente"].ToString());
                cml.cedula = clientes3["cedula"].ToString();
                cml.nombre = clientes3["nombre"].ToString();
                cml.apellido = clientes3["apellido"].ToString();
                cml.email = clientes3["email"].ToString();
                cml.direccion = clientes3["direccion"].ToString();
                cml.telefono = clientes3["telefono"].ToString();

                lista3.Add(cml);
            }

            con1.closeConection();
            con2.closeConection();
            con3.closeConection();

            ViewBag.Cliente_Sucursal1 = lista1;
            ViewBag.Cliente_Sucursal2 = lista2;
            ViewBag.Cliente_Sucursal3 = lista3;

            return View();
        }
    }
}

ETL_Aplicada/Controllers/EmpleadoController.cs
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Threading.Tasks;
using ETL_Aplicada.Models;
using Microsoft.AspNetCore.Mvc;

namespace ETL_Aplicada.Controllers
{
    public class EmpleadoController : Controller
    {
        public IActionResult Index()
        {
            ConexionModel con1 = new ConexionModel("Sucursal1");
            ConexionModel con2 = new ConexionModel("Sucursal2");
            ConexionModel con3 = new ConexionModel("Sucursal3");

            SqlDataReader dr1 = con1.consultar("SELECT * FROM Productos");
            SqlDataReader dr2 = con2.consultar("SELECT * FROM Productos");
            SqlDataReader dr3 = con3.consultar("SELECT * FROM Productos");

            List<EmpleadoModel> lista1 = new List<EmpleadoModel>();
            List<EmpleadoModel> lista2 = new List<EmpleadoModel>();
            List<EmpleadoModel> lista3 = new List<EmpleadoModel>();

            while (dr1.Read())
            {
                EmpleadoModel temp = new EmpleadoModel();
                temp.id_empleado = int.Parse(dr1["id_empleado"].ToString());
                temp.carnet = dr1["carne"].ToString();
                temp.cedula = dr1["cedula"].ToString();
                temp.nombre = dr1["nombre"].ToString();
                temp.apellido = dr1["apellido"].ToString();
                temp.email = dr1["email"].ToString();
                temp.telefono = dr1["telefono"].ToString();
                temp.direccion = dr1["direccion"].ToString();

                lista1.Add(temp);
            }

            while (dr2.Read())
            {
                EmpleadoModel temp = new EmpleadoModel();
                temp.id_empleado = int.Parse(dr2["id_empleado"].ToString());
                temp.carnet = dr2["carne"].ToString();
                temp.cedula = dr2["cedula"].ToString();
                temp.nombre = dr2["nombre"].ToString();
                temp.apellido = dr2["apellido"].ToString();
                temp.email = dr2["email"].ToString();
                temp.telefono = dr2["telefono"].ToString();
                temp.direccion = dr2["direccion"].ToString();

                lista2.Add(temp);
            }

            while (dr3.Read())
            {
                EmpleadoModel temp = new EmpleadoModel();
                temp.id_empleado = int.Parse(dr3["id_empleado"].ToString());
                temp.carnet = dr3["carne"].ToString();
                temp.cedula = dr3["cedula"].ToString();
                temp.nombre = dr3["nombre"].ToString();
                temp.apellido = dr3["apellido"].ToString();
                temp.email = dr3["email"].ToString();
                temp.telefono = dr3["telefono"].ToString();
                temp.direccion = dr3["direccion"].ToString();

                lista3.Add(temp);
            }

            con1.closeConection();
            con2.closeConection();
            con3.closeConection();

            ViewBag.Empleado_Sucursal1 = lista1;
            ViewBag.Empleado_Sucursal2 = lista2;
            ViewBag.Empleado_Sucursal3 = lista3;


            return View();
        }
    }
}

ETL_Aplicada/Controllers/ProductoController.cs
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Threading.Tasks;
using ETL_Aplicada.Models;
using Microsoft.AspNetCore.Mvc;

namespace ETL_Aplicada.Controllers
{
    public class ProductoController : Controller
    {
        public IActionResult Index()
        {
            ConexionModel con1 = new ConexionModel("Sucursal1");
            ConexionModel con2 = new ConexionModel("Sucursal2");
            ConexionModel con3 = new ConexionModel("Sucursal3");

            SqlDataReader dr1 = con1.consultar("SELECT * FROM Productos");
            SqlDataReader dr2 = con2.consultar("SELECT * FROM Productos");
            SqlDataReader dr3 = con3.consultar("SELECT * FROM Productos");

            List<ProductoModel> lista1 = new List<ProductoModel>();
            List<ProductoModel> lista2 = new List<ProductoModel>();
            List<ProductoModel> lista3 = new List<ProductoModel>();

            while (dr1.Read())
            {
                ProductoModel temp = new ProductoModel();
                temp.id_producto = int.Parse(dr1["id_producto"].ToString());
                temp.codigo_producto = dr1["codigo_producto"].ToString();
                temp.id_proveedor = int.Parse(dr1["id_proveedor"].ToString());
                temp.nombre = dr1["nombre"].ToString();
                temp.cantidad = int.Parse(dr1["cantidad"].ToString());
                temp.precio = dr1["precio"].ToString();

                lista1.Add(temp);
            }

            while (dr2.Read())
            {
                ProductoModel temp = new ProductoModel();
                temp.id_producto = int.Parse(dr2["id_producto"].ToString());
                temp.codigo_producto = dr2["codigo_producto"].ToString();
                temp.id_proveedor = int.Parse(dr2["id_proveedor"].ToString());
                temp.nombre = dr2["nombre"].ToString();
                temp.cantidad = int.Parse(dr2["cantidad"].ToString());
                temp.precio = dr2["precio"].ToString();

                lista2.Add(temp);
            }

            while (dr3.Read())
            {
                ProductoModel temp = new ProductoModel();
                temp.id_producto = int.Parse(dr3["id_producto"].ToString());
                temp.codigo_producto = dr3["codigo_producto"].ToString();
                temp.id_proveedor = int.Parse(dr3["id_proveedor"].ToString());
                temp.nombre = dr3["nombre"].ToString();
                temp.cantidad = int.Parse(dr3["cantidad"].ToString());
                temp.precio = dr3["precio"].ToString();

                lista3.Add(temp);
            }

            con1.closeConection();
            con2.closeConection();
            con3.closeConection();

            ViewBag.Producto_Sucursal1 = lista1;
            ViewBag.Producto_Sucursal2 = lista2;
            ViewBag.Producto_Sucursal3 = lista3;

            return View();
        }
    }
}

ETL_Aplicada/Controllers/ProveedorController.cs
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Threading.Tasks;
using ETL_Aplicada.Models;
using Microsoft.AspNetCore.Mvc;

namespace ETL_Aplicada.Controllers
{
    public class ProveedorController : Controller
    {
        public IActionResult Index()
        {
            ConexionModel con1 = new ConexionModel("Sucursal1");
            ConexionModel con2 = new ConexionModel("Sucursal2");
            ConexionModel con3 = new ConexionModel("Sucursal3");

            SqlDataReader clientes1 = con1.consultar("SELECT * FROM Proveedor");
            SqlDataReader clientes2 = con2.consultar("SELECT * FROM Proveedor");
            SqlDataReader clientes3 = con3.consultar("SELECT * FROM Proveedor");

            List<ProveedorModel> lista1 = new List<ProveedorModel>();
            List<ProveedorModel> lista2 = new List<ProveedorModel>();
            List<ProveedorModel> lista3 = new List<ProveedorModel>();

            while (clientes1.Read())
            {
                ProveedorModel cml = new ProveedorModel();
                cml.id_proveedor = int.Parse(clientes1["id_proveedor"].ToString());
                cml.nombre = clientes1["nombre"].ToString();
                cml.email = clientes1["email"].ToString();
                cml.direccion = clientes1["direccion"].ToString();
                cml.telefono = clientes1["telefono"].ToString();

                lista1.Add(cml);
            }

            while (clientes2.Read())
            {
                ProveedorModel cml = new ProveedorModel();
                cml.id_proveedor = int.Parse(clientes2["id_proveedor"].ToString());
                cml.nombre = clientes2["nombre"].ToString();
                cml.email = clientes2["email"].ToString();
                cml.direccion = clientes2["direccion"].ToString();
                cml.telefono = clientes2["telefono"].ToString();

                lista2.Add(cml);
            }

            while (clientes3.Read())
            {
                ProveedorModel cml = new ProveedorModel();
                cml.id_proveedor = int.Parse(clientes3["id_proveedor"].ToString());
                cml.nombre = clientes3["nombre"].ToString();
                cml.email = clientes3["email"].ToString();
                cml.direccion = clientes3["direccion"].ToString();
                cml.telefono = clientes3["telefono"].ToString();

                lista3.Add(cml);
            }

            con1.closeConection();
            con2.closeConection();
            con3.closeConection();

            ViewBag.Proveedor_Sucursal1 = lista1;
            ViewBag.Proveedor_Sucursal2 = lista2;
            ViewBag.Proveedor_Sucursal3 = lista3;


            return View();
        }
    }
}

ETL_Aplicada/Views/Producto/Index.cshtml
<div class="container">
    <div class="jumbotron">

        <div class="row">

            <div class="col-md-9">
                <div class="btn-group">
                    <a class="btn btn-primary btn-lg" asp-area="" asp-controller="Cliente" asp-action="Index">Clientes</a>
                    <a class="btn btn-primary btn-lg" asp-area="" asp-controller="Producto" asp-action="Index">Productos</a>
                    <a class="btn btn-primary btn-lg" asp-area="" asp-controller="Proveedor" asp-action="Index">Proveedores</a>
                    <a class="btn btn-primary btn-lg" asp-area="" asp-controller="Empleado" asp-action="Index">Empleados</a>
                    <a class="btn btn-primary btn-lg" asp-area="" asp-controller="Vestas" asp-action="Index">Ventas</a>
                </div>
            </div>
            <div class="col-md-3">
                <div class="btn-group btn-group-toggle" data-toggle="buttons">
                    <a class="btn btn-primary btn-lg" asp-area="" asp-controller="ETL" asp-action="Index">E T L</a>
                </div>
            </div>

        </div>

    </div>
    @model ProductoModel
    <div class="jumbotron">
        <ul class="nav nav-tabs" id="myTab" role="tablist">
            <li class="nav-item">
                <a class="nav-link active" id="home-tab" data-toggle="tab" href="#sucursal1" role="tab" aria-controls="home" aria-selected="true">Sucursal 1</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" id="profile-tab" data-toggle="tab" href="#sucursal2" role="tab" aria-controls="profile" aria-selected="false">Sucursal 2</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" id="contact-tab" data-toggle="tab" href="#sucursal3" role="tab" aria-controls="contact" aria-selected="false">Sucursal 3</a>
            </li>
        </ul>
        <div class="tab-content" id="myTabContent">
            <div class="tab-pane fade show active" id="sucursal1" role="tabpanel" aria-labelledby="home-tab">
                <table class="table table-striped">
                    <tr>
                        <th>ID</th>
                        <th>C&oacute;digo</th>
                        <th>Nombre</th>
                        <th>Precio</th>
                        <th>Cantidad</th>
                    </tr>
                    @foreach (ProductoModel temp in ViewBag.Producto_Sucursal1)
                    {
                        <tr>
                            <td>@temp.id_producto</td>
                            <td>@temp.codigo_producto</td>
                            <td>@temp.nombre</td>
                            <td>@temp.precio</td>
                            <td>@temp.cantidad</td>
                        </tr>

                    }
                </table>
            </div>
            <div class="tab-pane fade" id="sucursal2" role="tabpanel" aria-labelledby="profile-tab">
                <table class="table table-striped">
                    <tr>
                        <th>ID</th>
                        <th>C&oacute;digo</th>
                        <th>Nombre</th>
                        <th>Precio</th>
                        <th>Cantidad</th>
                    </tr>
                    @foreach (ProductoModel temp in ViewBag.Producto_Sucursal2)
                    {
                        <tr>
                            <td>@temp.id_producto</td>
                            <td>@temp.codigo_producto</td>
                            <td>@temp.nombre</td>
                            <td>@temp.precio</td>
                            <td>@temp.cantidad</td>
                        </tr>

                    }
                </table>
            </div>
            <div class="tab-pane fade" id="sucursal3" role="tabpanel" aria-labelledby="contact-tab">
                <table class="table table-striped">
                    <tr>
                        <th>ID</th>
                        <th>C&oacute;digo</th>
                        <th>Nombre</th>
                        <th>Precio</th>
                        <th>Cantidad</th>
                    </tr>
                    @foreach (ProductoModel temp in ViewBag.Producto_Sucursal3)
                    {
                        <tr>
                            <td>@temp.id_producto</td>
                            <td>@temp.codigo_producto</td>
                            <td>@temp.nombre</td>
                            <td>@temp.precio</td>
                            <td>@temp.cantidad</td>
                        </tr>

                    }
                </table>
            </div>
        </div>
    </div>
</div>